services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: calorie_buddy
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: